version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/containerstop.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/containerstart.sh
      timeout: 100
      runas: root
      


