version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /python-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /python-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /python-app/docker-registry/url
phases:
  install:
   runtime-versions:
     python: 3.11
  pre_build:
    commands:
      - pip install -r python-app/req.txt
  build:
    commands:
      - cd python-app
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-app:latest" .
      - docker push "docker.io/muneendrasingam/python-app:latest"
  post_build:
    commands:
      - echo "Build is Successful"
  
